# Generated by Django 5.1.6 on 2025-03-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_weightrecord_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
