# Generated by Django 5.1.6 on 2025-04-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/do4epjo9m/image/upload/v1/avatars/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
