# Generated by Django 5.1.6 on 2025-04-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='https://asset.cloudinary.com/do4epjo9m/121aa14bcc0140bc3f397f4be44adb0c', null=True, upload_to='avatars/'),
        ),
    ]
