# Generated by Django 5.1.6 on 2025-04-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/do4epjo9m/image/upload/v1745842509/default_avatar.png.jpg', null=True, upload_to='avatars/'),
        ),
    ]
