# Generated by Django 5.1.6 on 2025-04-21 15:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0017_remove_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories', models.PositiveIntegerField(default=0)),
                ('proteins', models.PositiveIntegerField(default=0)),
                ('fats', models.PositiveIntegerField(default=0)),
                ('carbs', models.PositiveIntegerField(default=0)),
                ('goal_calories', models.PositiveIntegerField(default=0)),
                ('goal_proteins', models.PositiveIntegerField(default=0)),
                ('goal_fats', models.PositiveIntegerField(default=0)),
                ('goal_carbs', models.PositiveIntegerField(default=0)),
                ('water_intake', models.PositiveIntegerField(default=0, help_text='In milliliters')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdetails')),
            ],
            options={
                'verbose_name': 'Daily Nutrition',
                'verbose_name_plural': 'Daily Nutrition',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('calories', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('proteins', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.dailynutrition')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
