# Generated by Django 5.1.6 on 2025-04-21 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynutrition',
            name='water_intake',
            field=models.PositiveIntegerField(default=0, help_text='In milliliters', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
