# Generated by Django 5.1.6 on 2025-04-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_auto_20250421_1602'),
    ]

    operations = [
    ]
