# Generated by Django 5.1.6 on 2025-04-22 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_fooditem_mealfooditem_meal_food_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('calories', models.PositiveIntegerField(help_text='Calories per 100g')),
                ('proteins', models.DecimalField(decimal_places=2, help_text='Proteins per 100g', max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, help_text='Fats per 100g', max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, help_text='Carbs per 100g', max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='mealfooditem',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='food_items',
        ),
        migrations.RemoveField(
            model_name='mealfooditem',
            name='meal',
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in grams', max_digits=6)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.meal')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(through='nutrition.MealIngredient', to='nutrition.ingredient'),
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.DeleteModel(
            name='MealFoodItem',
        ),
    ]
