# Generated by Django 5.1.6 on 2025-03-26 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_alter_meal_calories_alter_meal_carbs_alter_meal_fats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailynutrition',
            options={'verbose_name': 'Daily Nutrition', 'verbose_name_plural': 'Daily Nutrition'},
        ),
        migrations.RenameField(
            model_name='dailynutrition',
            old_name='total_calories',
            new_name='calories',
        ),
    ]
