# Generated by Django 5.1.6 on 2025-03-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_alter_dailynutrition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynutrition',
            name='goal_calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailynutrition',
            name='goal_carbs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailynutrition',
            name='goal_fats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailynutrition',
            name='goal_proteins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
