# Generated by Django 5.1.6 on 2025-04-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_fooditem_remove_meal_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='food_items',
        ),
        migrations.DeleteModel(
            name='MealFoodItem',
        ),
    ]
