# Generated by Django 5.1.6 on 2025-04-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_remove_meal_food_items_delete_mealfooditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
