# Generated by Django 5.1.6 on 2025-03-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_alter_dailynutrition_options_alter_meal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailynutrition',
            options={'verbose_name': 'Daily Nutrition', 'verbose_name_plural': 'Daily Nutrition'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={},
        ),
        migrations.RemoveField(
            model_name='dailynutrition',
            name='goal_calories',
        ),
        migrations.RemoveField(
            model_name='dailynutrition',
            name='goal_carbs',
        ),
        migrations.RemoveField(
            model_name='dailynutrition',
            name='goal_fats',
        ),
        migrations.RemoveField(
            model_name='dailynutrition',
            name='goal_proteins',
        ),
        migrations.RemoveField(
            model_name='dailynutrition',
            name='water_intake',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='notes',
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fats',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='proteins',
            field=models.PositiveIntegerField(),
        ),
    ]
