# Generated by Django 5.1.6 on 2025-04-22 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_delete_fooditem'),
        ('users', '0017_remove_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('proteins', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=1, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=1, max_digits=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userdetails')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
