# Generated by Django 5.1.6 on 2025-03-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0011_alter_dailynutrition_options_alter_meal_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailynutrition',
            name='water_intake',
        ),
    ]
