# Generated by Django 5.1.6 on 2025-04-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0012_alter_fooditem_options_alter_fooditem_calories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
