# Generated by Django 5.1.6 on 2025-03-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0012_remove_dailynutrition_water_intake'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynutrition',
            name='water_intake',
            field=models.PositiveIntegerField(default=0, help_text='In milliliters'),
        ),
    ]
