# Generated by Django 5.1.6 on 2025-04-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0013_dailynutrition_water_intake'),
    ]

    operations = [
    ]
