# Generated by Django 5.1.6 on 2025-04-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0013_alter_fooditem_options_remove_fooditem_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={},
        ),
    ]
