# Generated by Django 5.1.6 on 2025-04-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0014_auto_20250421_1311'),
    ]

    operations = [
    ]
