# Generated by Django 5.1.6 on 2025-04-23 16:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0015_remove_fooditem_updated_at_fooditem_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition.fooditem'),
        ),
        migrations.AddField(
            model_name='meal',
            name='grams',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
