# Generated by Django 4.2.20 on 2025-06-03 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_userprofile_avatar'),
        ('nutrition', '0016_meal_food_item_meal_grams'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('video_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('calories_burned', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdetails')),
            ],
            options={
                'unique_together': {('user', 'date', 'video_id')},
            },
        ),
    ]
