# Generated by Django 4.2.20 on 2025-06-06 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_userprofile_avatar'),
        ('nutrition', '0017_workoutcompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnedCaloriesVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('video_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('calories_burned', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('done', 'Done'), ('skip', 'Skip')], default='skip', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdetails')),
            ],
            options={
                'unique_together': {('user', 'date', 'video_id')},
            },
        ),
        migrations.DeleteModel(
            name='WorkoutCompletion',
        ),
    ]
