# Generated by Django 4.2.20 on 2025-06-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0018_burnedcaloriesvideo_delete_workoutcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynutrition',
            name='burned_extra_calories',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
